[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "stlkernel"
version = "0.1.0"
description = "Kernel for Signal Temporal Logic"
dependencies = [
    "torch",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["src"]
